name: jupyterhub-rtc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyterhub=4.0.2
  - jupyterlab=4.0
  - requests
  - jupyter-collaboration=1.2.0
  - pip:
    - jupyterlab-rtc-hub-settings==0.1.3
    - jupyterlab-link-share==0.3.0
